server:
  port: 8801
spring:
  application:
    name: zuul-proxy
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
    fetch-registry: true
    register-with-eureka: true
zuul:
  routes:   #服务配置路由
    user-service:
      path: /userService/**
    feign-service:
      path: /feignService/**
  prefix: /proxy  #给网关路由添加前缀
  #Zuul在请求路由时，默认会过滤掉一些敏感的头信息，以下配置可以防止路由时的Cookie及Authorization的丢失：
  sensitive-headers: Cookies,Set-Cookie/Authorization #配置过滤敏感的请求头信息，设置为空不会过滤
  add-host-header: true #设置为true重定向会添加host请求头，Zuul在请求路由时，不会设置最初的host头信息
#  ignored-services: user-service,feign-service #关闭默认路由配置
management:  #开启查看路由端点
  endpoints:
    web:
      exposure:
        include: 'routes'
