server:
  port: 8701
spring:
  application:
    name: feign-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
    fetch-registry: true
    register-with-eureka: true
feign:
  hystrix:
    enabled: true #在Feign中开始Hystrix
logging:
  level:
    com.itz.cloud.service.UserService: debug